name: Testing

on:
  push:
    branches: [ "main" ]
    tags:
      - "*"
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

#  schedule:
#    - cron: '* */1 * * *'

concurrency:
  group: geektrust
  cancel-in-progress: true

env:
  mode: 'dev'

jobs:
  test:
    runs-on: ubuntu-latest
#

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10 on ubuntu-latest
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Rider Sharing
        run: |
          cd rider-sharing
          python geektrust.py
          python -m unittest discover
          

  all:
    runs-on: ubuntu-latest
#

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10 on ubuntu-latest
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: All problems
        run: |
          # Find all folders containing geektrust.py

          folders=$(find . -name geektrust.py -exec dirname {} \;)
  
          for folder in $folders; do
              cd "$folder" || continue
              echo "build $folder"
              python geektrust.py
              echo "unit testing $folder"
              python -m unittest discover
              cd ..
          done
        
        
          
